[package]
name = "chess"
version = "0.1.0"
edition = "2021"
lto = "true"

[lib]
name = "chess"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
rand = "0.8.5"
